[[route]]
host = "https://www.baidu.com"
# path = "/"
code = 202
# body = "html"
payload='{"yes"}'
headers=["Content-Type: application/json"]

[[route]]
host = "http://bilibili.com"
# path = "/test"
code = 403
# body = "htmls"
headers = ["Content-Type: text/html"]