version: '3.5'
services:
  h1:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    hostname: ${HOST_1}
    volumes:
      - "./main.yaml:/home/stubby4j/data/main.yaml"
    environment:
      YAML_CONFIG: main.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 80
      WITH_ARGS: "--debug --watch"
 
  h2:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    hostname: ${HOST_2}
    volumes:
      - "./main.yaml:/home/stubby4j/data/main.yaml"
    environment:
      YAML_CONFIG: main.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 80
      WITH_ARGS: "--debug --watch"

  h3:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    hostname: ${HOST_3}
    volumes:
      - "./main.yaml:/home/stubby4j/data/main.yaml"
    environment:
      YAML_CONFIG: main.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 80
      WITH_ARGS: "--debug --watch"
      
networks:
  default:
    external:
      name: ${NETWORK}
   